# Generated by Django 5.2.4 on 2025-07-16 07:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dtpo9ceis/image/upload/v1752649954/afwhofteawmgxenoxswj.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
