# Generated by Django 5.2.4 on 2025-07-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
