# Generated by Django 5.2.4 on 2025-07-16 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dtpo9ceis/image/upload/v1752648759/vswcnd9rltn1mqwr2rwl.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
